name: build
on: [pull_request,push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    needs: lint-chart
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: build & push docker image
        run: |
          set -e
          echo "Build Docker image with tag / travis build number ${TRAVIS_BUILD_NUMBER} for DockerHubs ${DOCKER_REGISTRY}/${GITHUB_USERNAME}/${DOCKER_REPOSITORY} repo"
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
          docker build --pull --no-cache -t ${DOCKER_REGISTRY}/${GITHUB_USERNAME}/${DOCKER_REPOSITORY}:latest -t ${DOCKER_REGISTRY}/${GITHUB_USERNAME}/${DOCKER_REPOSITORY}:${TRAVIS_BUILD_NUMBER} .
          docker push ${DOCKER_REGISTRY}/${GITHUB_USERNAME}/${DOCKER_REPOSITORY}:${TRAVIS_BUILD_NUMBER}
          docker push ${DOCKER_REGISTRY}/${GITHUB_USERNAME}/${DOCKER_REPOSITORY}:latest
