name: build
on: [pull_request,push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: debug
        run: printenv | sort
      - name: build & push docker image
        run: .github/workflows/build.sh
